language: cpp
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libjpeg-dev
      - libpng-dev

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi; fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script: make

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
