language: cpp
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libjpeg-dev
      - libpng-dev
      - libclblas-dev
      - opencl-headers

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew tap homebrew/science && brew install clblas; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - if [ "$TEST_SUITE" = "reference" ]; then cmake -DCMAKE_BUILD_TYPE=Release ..; fi
  - if [ "$TEST_SUITE" = "opencl" ]; then cmake -DCMAKE_BUILD_TYPE=Release -DCN24_BUILD_OPENCL -DCN24_BUILD_OPENCL_CLBLAS ..; fi

script: make

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TEST_SUITE=opencl
  - TEST_SUITE=reference
